### ISSUE TITLE
软件处理进度到第29883项目时停止工作，软件没有崩溃，电脑没有死机

### ISSUE THREAD

**Issue by Wind-stormger** [PPJUST/DouDup#2]
软件版本是2.0，cpu为8核16线程 ryzen 3700x，内存为32G。

从昨晚开始，已重复运行多次，且也清理了缓存重新测试，都停止在第29883。

问题截图如下：
![QQ20240917-105603](https://github.com/user-attachments/assets/5652315b-18f2-48ac-b59c-3af66e113f00)
![QQ20240917-095401](https://github.com/user-attachments/assets/bb5afc52-8166-4ed2-ad2c-568438993924)
![QQ20240917-001820](https://github.com/user-attachments/assets/02e50c16-104d-41e1-9490-ed0ce29410a2)

**Comment by PPJUST** [comment]
ssim选项不要选中再试试。我之前也碰到相似匹配这步时报错的问题了，还以为是ssim方法的问题简单修了之后就没管了，那应该是没修好

**Comment by Wind-stormger** [comment]
ssim方法是何物？ahash，phash，dhash各有什么不同与优劣之分？
